version: '3.8'

services:
  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD= # POSTGRES_DB_PASSWORD
  #   container_name: postgres
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

  # pgadmin:
  #   image: pgadmin4
  #   restart: always
  #   container_name: nest-pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL= # PG_EMAIL
  #     - PGADMIN_DEFAULT_PASSWORD= # PG_PASSWORD
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db

  # mongo:
  #   image: mongo:6.0
  #   container_name: mongodb
  #   restart: always
  #   ports:
  #     - '27017:27017'
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME= # MONGO_DB_NAME
  #     - MONGO_INITDB_ROOT_PASSWORD= # MONGO_DB_USER
