# Sample github action configuration for building and pushing docker images to docker hub
name: Build and Deploy

on: 
    push: 
        branches: 
            - develop
    pull_request: 
        branches: 
            - master

jobs: 
    build-and-deploy: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag nestjs-boilerplate-api
           
